/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;

public class App {
//    public String getGreeting() {
//        return "Hello world.";
//    }
//
    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        Quote[] aQuote = gson.fromJson(new FileReader("json/recentquotes.json"), Quote[].class);

        for (int i = 0; i < aQuote.length; i++) {
            System.out.println(aQuote[i].getText() + "\n\t- " + aQuote[i].getAuthor());
        }
    }
}

